/*************************************************************************
*************************************************************************
This plugin is free software: you can redistribute 
it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation, either version 3 of the License, or
later version. 

This plugin is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this plugin.  If not, see <http://www.gnu.org/licenses/>.
*************************************************************************
*************************************************************************/
#if defined _umc_playerlimits_included
    #endinput
#endif
#define _umc_playerlimits_included

#define PLAYERLIMIT_KEY_MAP_MIN "min_players"
#define PLAYERLIMIT_KEY_MAP_MAX "max_players"
#define PLAYERLIMIT_KEY_GROUP_MIN "default_min_players"
#define PLAYERLIMIT_KEY_GROUP_MAX "default_max_players"